Allow disabling the monitoring when starting a test network.
paritytech/parity-bridges-common pull request #689
Opened 2021-01-29 15:54 UTC by tomusdrw

2021-01-29 17:35 UTC, HCastano requested changes
While I like this, the `--no-monitoring` option doesn't work. I run into the following error:

```
❯ ./deployments/run.sh rialto-millau --no-monitoring

...

+ docker-compose --project-directory . ... -f ./monitoring/disabled.yml up -d
Pulling grafana-dashboard (scratch:)...
ERROR: 'scratch' is a reserved name
```

The [image](https://hub.docker.com/_/scratch/) page on Docker Hub says that:

> While scratch appears in Docker’s repository on the hub, you can’t pull it, run it, or tag any image with the name scratch.

We'll need some other "dummy" image to use here.

2021-01-29 17:35 UTC, HCastano commented on deployments/run.sh
> +function show_help () {
Nice touch 👌

2021-01-29 17:35 UTC, HCastano commented on deployments/run.sh
> +      shift
TIL about `shift`

2021-02-01 11:44 UTC, tomusdrw commented
> While I like this, the --no-monitoring option doesn't work. I run into the following error:

Apologies, I was pretty sure I tested it and it worked, but I must have mix something up. Updated to use `alpine` image instead.

2021-02-01 20:31 UTC, HCastano approved these changes
Looks good!

2021-02-01 20:31 UTC, merged